#!/bin/bash

# Attempt provide Kate's isvg
# https://twitter.com/thingskatedid/status/1316074032379248640

if [ -n "$1" ] ; then
    infile="$1" ; shift
else
    infile=/dev/stdin
fi

if [ ! -x "$(which rsvg-convert)" ] ; then
    echo "Not librsvg2-bin, installing:" >&2
    sudo apt install librsvg2-bin
fi

rsvg-convert -b '#777777' -f png "$infile" | kitty +kitten icat --align=left 
