#!/bin/bash

# A rofi to do stuff with things in the clipboard.

mydir="$(dirname "$BASH_SOURCE")"

menu_lines () {
    cat <<EOF
google
myougiden
type
EOF
}

typeit () {
    xdotool type "$(xclip -selection primary -o)"
}
translateit () {
    "$mydir/translate" xclip primary
}
myougidenit () {
    myougiden-zenity "$(xclip -selection primary -o)"
}

got=$(menu_lines | rofi -dmenu)
${got}it


